-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.orders
(
    id_distributor "char",
    id_cabang "char",
    id_customer "char",
    id_invoice "char",
    id_brand "char",
    tanggal date,
    jumlah_barang numeric,
    unit numeric,
    id_barang "char",
    PRIMARY KEY (id_invoice)
);

CREATE TABLE IF NOT EXISTS public.customer
(
    id_customer "char",
    nama "char",
    id_sales "char",
    sales "char"
);

CREATE TABLE IF NOT EXISTS public.barang
(
    id_barang "char",
    nama_barang "char",
    tipe "char",
    kemasan "char"
);

CREATE TABLE IF NOT EXISTS public.distributor
(
    id_distributor "char",
    nama_distributor "char",
    kota "char"
);

CREATE TABLE IF NOT EXISTS public.cabang
(
    id_cabang "char",
    nama_cabang "char",
    alamat "char",
    kota "char"
);

CREATE TABLE IF NOT EXISTS public.brand
(
    id_brand "char",
    nama_brand "char",
    tahun date
);

ALTER TABLE IF EXISTS public.orders
    ADD FOREIGN KEY (id_brand)
    REFERENCES public.brand (id_brand) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.orders
    ADD FOREIGN KEY (id_distributor)
    REFERENCES public.distributor (id_distributor) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.orders
    ADD FOREIGN KEY (id_cabang)
    REFERENCES public.cabang (id_cabang) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.orders
    ADD FOREIGN KEY (id_barang)
    REFERENCES public.barang (id_barang) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.orders
    ADD FOREIGN KEY (id_customer)
    REFERENCES public.customer (id_customer) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;